### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by meaton-potatoes** [sophi-li/affirmations#1]
I was going to submit a pull request, but I think the repo might have a setting enabled that disallows pull requests?

**Comment by sophi-li** [comment]
Thanks so much, Melissa! This is my first code review and I'm not too sure how to enable the settings. I think I've left all my settings to default (Screenshots attached).

Did a bunch of Googling but I can't seem to find something that'll get it to allow. I also am not sure which is the feature that allows for PRs! :( (https://help.github.com/en/github/administering-a-repository/enabling-required-reviews-for-pull-requests)

I've also left my branch to its default settings. Do you have any guesses on what the issue might be? 

I did add you as a collaborator so I think it should work! :) https://github.com/sophi-li/affirmations/invitations

Lmk if it still doesn't work!

![Screen Shot 2019-11-01 at 9 35 16 PM](https://user-images.githubusercontent.com/26865116/68066121-1e2b1000-fcf0-11e9-94a3-741de9e70624.png)
![Screen Shot 2019-11-01 at 9 35 27 PM](https://user-images.githubusercontent.com/26865116/68066123-24b98780-fcf0-11e9-9282-98350b4e8451.png)
